Added WIndows 2022 and Updated CONTRIBUTING.md
chef/fauxhai pull request #24
Opened 2023-11-15 14:20 UTC by jjperry

Added Windows 2022 Fauxhai data
Updated CONTRIBUTING.md steps

## Description

Adding the Windows 2022 Fauxhai data adds support for Windows 2022 Chefspec testing. 

Updating the CONTRIBUTING.md gives the correct steps required to validate and verify the changes on CentOS 9 Stream and CentOS 7 Ruby development servers. 

## Related Issue

#22 
#23 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] I have run the pre-merge tests locally and they pass.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [X] All new and existing tests passed.
- [ ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-11-21 21:08 UTC, tpowell-progress approved these changes

2023-11-21 21:11 UTC, tpowell-progress requested changes
Looks like there's a breakage on the mocker_spec.rb
https://github.com/chef/fauxhai/actions/runs/6878582286/job/18907141443?pr=24

2023-11-21 21:14 UTC, dafyddcrosby commented on PLATFORMS.md
> +- 9
Looks like this got leaked from #21 along with the rocky line below

2023-11-27 13:30 UTC, jjperry commented on PLATFORMS.md
> +- 9
I'm not following. 

Both are in the repo I pulled down to add RedHat 9 and Windows2022.  AlmaLinux 9 was in the 2023-02-03 release and Rocky 9 in the 2023-05-05.

2023-12-05 21:51 UTC, tpowell-progress approved these changes

2023-12-05 21:52 UTC, merged